### ISSUE TITLE
Showing hourly instead of daily

### ISSUE THREAD

**Issue by ljmerza** [sgttrs/lovelace-weather-card-chart#4]
I added this card and it's only showing hourly. I tried to manually set daily but still showing hourly.

```yaml
- type: 'custom:weather-card-chart'
  title: Weather
  weather: weather.dark_sky
  mode: daily
```

![image](https://user-images.githubusercontent.com/4085765/52281633-7f25e300-292c-11e9-86aa-de8a335377f2.png)
